### ISSUE TITLE
name transfer.

### ISSUE THREAD

**Issue by jdalton** [mgan59/DocDown#3]
Hi Morgan!

I have a similar project [docdown](https://github.com/jdalton/docdown) that's been around since 2011 in PHP but as recently been ported to JS. I was wondering if you would be open to releasing the name docdown on npm. If so you can unpublish or add me as an owner.

Thanks!
-JDD

**Comment by mgan59** [comment]
@jdalton sorry for the delay in getting back to you on this, things have been crazy the past few weeks.  Will be happy to turn it over as I'm no longer actively working working on this module.  Will add you as the owner and you can take it over.

cheers

**Comment by jdalton** [comment]
Awesome! Thank you!

**Comment by mgan59** [comment]
@jdalton should be all set, let me know if there are any issues.

**Comment by jdalton** [comment]
The [package](https://www.npmjs.com/package/docdown) doesn't have me listed yet. You have to do:

``` bash
$ npm owner add jdalton
```

**Comment by mgan59** [comment]
@jdalton Sorry been traveling this weekend.  I ran the `owner` command that evening

``` sh
morgancraft@morgans-mbp:~/Documents/projects$ npm owner add jdalton docdown
morgancraft@morgans-mbp:~/Documents/projects$ npm owner ls docdown
mgan59 <mgan***@***.com>
jdalton <jo*****dalton@***.com>
```

**Comment by mgan59** [comment]
@jdalton I see it is in your packages list now on npm.  Might of been a sync/replication issue with npm/couchdb.  

Let me know if your all set.  Cheers!

**Comment by jdalton** [comment]
All set thanks!
